# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by Debian postinst script
# Date: Mon, 05 Nov 2012 21:16:50 +0100

*               @ALL          1
*               @user         8
hrm:*         @ALL          0
hrm:*         pgomersbach   8
hrm:*         mdekoning     8
hrm           @ALL          0
hrm         pgomersbach   8
hrm         mdekoning   8
