name    'puppetlabs-mssql'
version '0.1.0'
source  'https://github.com/puppetlabs/puppetlabs-mssql'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Microsoft SQL Server Module'
description 'Microsft SQL Server Installation Module for Puppet'
project_page 'https://github.com/puppetlabs/puppetlabs-mssql'

dependency 'puppetlabs/dism', '>= 0.1.0'
